### ISSUE TITLE
LangStringSets in JSON

### ISSUE THREAD

**Issue by sebbader** [aas-core-works/aas-core-meta#128]
As @mjacoby states in his review of another project (https://github.com/eclipse-digitaltwin/aas4j/pull/3#discussion_r905789705), the representation of LangStringSets in JSON deviates to statements of the official publication. Currently it's:

`
{
  "langStrings": [
     {
       "language": "en-us",
       "text": "An Example Asset Administration Shell for the test application"
    },
    {
       "language": "de",
       "text": "Ein Beispiel-Verwaltungsschale für eine Test-Anwendung"
     }
  ]
}
`

while the entry about LangStringSets in table 6, page 96 AAS Part 1 v3.0RC02 says that this one should be correct:

`
[
     {
       "language": "en-us",
       "text": "An Example Asset Administration Shell for the test application"
    },
    {
       "language": "de",
       "text": "Ein Beispiel-Verwaltungsschale für eine Test-Anwendung"
     }
 ]
`

**Comment by mristin** [comment]
@sebbader please correct me if I didn't get it right: you would like to remove the class `LangStringSet` and replace it everywhere with a list of instances of `LangString`?

This also implies that the uniqueness constrain on the language would have to be replicated manually as an invariant in our meta-model. Are you sure the official text is unambiguous on this?

**Comment by mristin** [comment]
P.S. as far as I remember, the book was not clear on it. I'd rather have the book fixed, as defining a type in terms of a list is indeed uncommon.

**Comment by g1zzm0** [comment]
Table 6 of AAS Part 1 v3.0RC02 only shows "Value Examples". According to the specification, it's a set (=object) with the corresponding attribute defined by the plural S serialization rule.

**Comment by mristin** [comment]
I filed a finding for the next version of the meta-model to represent LangStringSet as an object.

**Comment by g1zzm0** [comment]
Let's move this topic to the specification and close this issue.

**Comment by g1zzm0** [comment]
Since there is a partial quantity relation between LangSting and LangStringSet, the LangStringSet is objectified in the metamodel according to the current state of the specification. In accordance with the general requirement of generalized serialization rules and no object-related exceptions, only the objectified variant is provided according to the current status. Consequently, the existing plural S serialization rule is applied.

**Comment by sebbader** [comment]
@g1zzm0 "Consequently, the existing plural S serialization rule is applied." means that e.g. `Referable/description` will change to `Referable/descriptions`?

**Comment by g1zzm0** [comment]
Not at all. According to the Spec `description` is a `LangStringSet`:
Python
` description: Optional["Lang_string_set"]`

JSON
`
"description": {
 "$ref": "#/definitions/LangStringSet"
 },
`

**Comment by sebbader** [comment]
Now I am confused. According to the Spec, `Referable/description` should look like this in the JSON Schema:

```
"description": {
    "type": "array",
    "items": {
        "$ref": "#/definitions/LangString"
    },
    "minItems": 1
}
```
(As LangStingSet is a 'Primitive' in the Spec terminology.)

**Comment by g1zzm0** [comment]
Please check if your file is up-to-date and read section 5.7.2.2 Referable Attributes on page 48.
Description if of type LangStringSet with Cardinaliy 0..1 and not of type LangString with Cardinality 0..*.
![image](https://user-images.githubusercontent.com/1814815/180247978-c8230c50-72a9-40a4-b737-7089a5e9bfdb.png)

**Comment by g1zzm0** [comment]
What is right or wrong depends on the design principles. As already mentioned, the serialization rules should be as generally applicable as possible. There should be as already discussed no single exceptions for individual model elements. By the intermediate representation, everything is objectified after the almost highest rule. No object instance in the intermediate representation leads automatically to a mismatch in each serialization, implementation etc..

**Comment by sebbader** [comment]
We obviously have a different information state on which design principles you follow for https://github.com/aas-core-works/aas-core-meta/blob/main/aas_core_meta/v3rc2.py . Having them sounds reasonable to me, so no objections on this level.
Just let me be frank about the implications which an appearance of `LangStringSet` in any of the schemas will have: _None of them is correct then and can be pushed to the admin-shell/aas-specs repo._
**This is definitely not what I want, as the results from this repo are highly relevant.**

At the moment, I have the feeling that we may be in one of the following two scenarios. Not sure which, honestly.
1. There is confusion how to treat the primitives of the spec (table 6). As `LangStringSet` is the only one representing an array, I understand (and as said, I have done it too) interpreting it as an independent entity is straight forward. Nevertheless, this is not what the table indicates, the desired representation also for the non-JSON Schemas is as I have noted above.
2. The design principles enforce the treatment of primitives as individual objects. In this case however, I would expect to also find a `BlobType`object, an `Identifier`object, `ContentType` and so on. If this is the way to go for the schema generation, I really would like to challenge the respective design principle...

**Comment by sebbader** [comment]
@g1zzm0 @mristin please reopen this issue. It's content is really critical for me, and I feel like the decision will have a significant impact, so the discussion should not happen in a closed issue. Thanks!

**Comment by mristin** [comment]
I am fine with both approaches, though I tend to leave it as a class for readability. The class currently has no further properties than "items", but we would need to duplicate the constraints that the languages are unique if we are to expand it to a list instead of a class.

Theoretically, we could introduce the concept of a *constrained list* just as we did with constrained primitives. For now, I'd stick with in-lining of invariants for simplicity if we decide to go with lists.

@sebbader please mind that we can not make the `langString` a primitive as we then can not map it to JSON and XML, at least not at the current development iteration of aas-core-codegen. This is obviously not the focus of the current discussion, but an important side remark.

**Comment by sebbader** [comment]
> (@sebbader I reopened the issue -- please feel free to re-open any issue directly in the future.)

Thanks! (I think I am missing permission to reopen an issue here...)

**Comment by mristin** [comment]
@sebbader sorry, I wasn't aware that the decision has been already made. We will implement the `LangStringSet` as lists and duplicate the invariants for now.

**Comment by mristin** [comment]
@g1zzm0 @sebbader let's please first finish and merge in #148, and finish the security part before we make this change.

**Comment by BirgitBoss** [comment]
@mristin We discussed this in the Joint working group of the AAS this week. The decision was as follows: Since LangStringSet is a Primitive and not a Class according to the specification 3.0.RC02 no extra tag for the type "LangStringSet" shall be added. So a description with type "LangStringSet" would look like this:

`---
“description”: [
  {
      "language":"EN", 
         "text":" This is a multi-language value in English."
  },
  { 
"language":"DE", 
"text":" Das ist ein Multi-Language-Wert in Deutsch."  
   }
]

**Comment by g1zzm0** [comment]
But we don't discussed to change every existing appearance of  LangStringSet with Cardinaliy 0..1 to the LangString with Cardinality 0..* and to delete LangStringSet. At least I don't remember such a discussion. However, it was already the end of the meeting and very hot. And after the third participant referred to this situation, it was perhaps not the best idea to start another type discussion. Nevertheless what should it be?

`description: Optional["Lang_string_set"]`
Or
`description: Optional[List ["Lang_string"]]`

**Comment by BirgitBoss** [comment]
In my understanding this is not needed to be changed in the metamodel because LangStringSet is already defined as a primitive. 

How Python deals with primitives I cannot tell but the result should be as documented in the comment before. In other languages there is no difference between

#define LangStringSet  list(langString)
description: LangStringSet

and

description: list(langString)

so I have difficulties to understand the problem.

**Comment by g1zzm0** [comment]
So we can close this issue again. Because there is still no need to change anything.

**Comment by mristin** [comment]
@g1zzm0 just for future readers: we indeed need to  remove the class `LangStringSet` and impose the invariants on the respective properties of the related classes.

**Comment by g1zzm0** [comment]
We will discuss a potential change to the metamodel and the resulting consequences on the next meeting.

**Comment by BirgitBoss** [comment]
Similar discussion here with Primitives: https://github.com/admin-shell-io/aas-specs/issues/48 is similar.

<aas:identification>
    <aas:identifier idType="IRI">
        www.admin-shell.io/aas-sample/2/0
    </aas:identifier>
</aas:identification>
is not correct.

The rules for Primitives need to be followed.  So it is:

<aas:identification>
        www.admin-shell.io/aas-sample/2/0
</aas:identification>

(in the meanwhile the name and type changed, so for RC02 it is:

<aas:id>
        www.admin-shell.io/aas-sample/2/0
</aas:id>

and not

<aas:id>
  <aas:identifier>
        www.admin-shell.io/aas-sample/2/0
  </aas:identifier>
</aas:id>

**Comment by mristin** [comment]
Re-opening as a reminder that we still need to implement this.
