### ISSUE TITLE
Convention for Enumeration Values

### ISSUE THREAD

**Issue by sebbader** [aas-core-works/aas-core-meta#99]
It would be great to have a consistent appearance for enums (all CAPITALIZED, CamelCase or camelCase). The problem is that the metamodel references XS datatypes, which do not follow any convention either. Nevertheless, it would be great to avoid inconsistencies of the same enum across different serialisations (I have checked JSON and RDF).

"Positive" example:
AasSubmodelElements (JSON: https://github.com/admin-shell-io/aas-specs/blob/5a03afda102560771115504f3b67e315a0fbe7f1/schemas/json/aas.json#L12 and RDF: https://github.com/admin-shell-io/aas-specs/blob/5a03afda102560771115504f3b67e315a0fbe7f1/schemas/rdf/rdf-ontology.ttl#L163)
both with CamelCase.

"Problematic" example:
DataTypeDefXsd (JSON: https://github.com/admin-shell-io/aas-specs/blob/5a03afda102560771115504f3b67e315a0fbe7f1/schemas/json/aas.json#L244 and RDF: https://github.com/admin-shell-io/aas-specs/blob/5a03afda102560771115504f3b67e315a0fbe7f1/schemas/rdf/rdf-ontology.ttl#L580, see also DataTypeDefRdf)
JSON follows the original style from XML Schema, with 'xs' as a prefix, while RDF is again CamelCase without any further prefixes.

Suggestion:
a) Let's use the original XML Schema notation both for JSON and RDF (also XML?) but without prefixes as JSON cannot reference to the source namespace anyway. (personally preferred at the moment)
b) Let's use CamelCase but also get rid of the namespace prefix in the JSON schema.

**Comment by mristin** [comment]
@sebbader thanks, a good point! The value of the enumeration literals as a string should be constant across all three schemas. If it is not then it's a bug.

XML and JSON allow for exact specification of enumeration literals, so the schemas use directly exact enumeration values from aas-core-meta. Could you please make a couple of (short) examples in RDF and I'll fix the RDF schema accordingly? I think the source of the problem is rather our/my lack of experience with RDF than anything else :-).

**Comment by g1zzm0** [comment]
In my opinion, we should strictly follow the book when it comes to naming conventions.

**Comment by mristin** [comment]
@sebbader this is probably  also related to your code generation?

Could we use the `label` for denoting the literal values? Then we can stick to whatever naming convention in RDF while we can still specify arbitrary string values (with/without namespaces *etc.*).
